[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Menno Steensma <mennosteensma@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
lib = { path = "../lib" }
chrono = "0.4" 
