[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Menno Steensma <mennosteensma@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.13.0"
regex = "1.8"
lib = { path = "../../lib/rustutils" }